### ISSUE TITLE
How to use with authenticated webdav?

### ISSUE THREAD

**Issue by ChielHackman** [funbox/shrine-webdav#6]
Hi there,

I'm implementing this gem and the webdav is returning a 401 Unauthorized.

Is there a simple way to add credentials for the webdav?

**Comment by climber73** [comment]
Thanks for the question! Currently there is no any auth. PRs are wellcome

**Comment by tuwilof** [comment]
nothing 😄

**Comment by panicwassano** [comment]
Hello ChielHackman. Now the gem supports basic auth, look PR https://github.com/funbox/shrine-webdav/pull/10
